config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "user#sign_in", :to => "user#sign_in"
  post "user/sign_in", :to => "sessions#create"
  post "user/sign_up", :to => "user#sign_up"
  get "user/sign_up", :to => "user#sign_up"
  get "user/sign_in", :to => "user#sign_in"
  delete "user/sign_out", :to => "sessions#destroy"
  get "user/dashboard", :to => "user#dashboard"
  get "user/expenses_with_user", :to => "user#expenses_with_user"
  get "user/friends_expenses", :to => "user#friends_expenses"

  get "user/add_expense", :to => "user#add_expense"
  post "user/add_expense", :to => "user#add_expense"

  get "user/settle_expense", :to => "user#settle_expense"
  post "user/settle_expense", :to => "user#settle_expense"
  get "user/all_expenses_log", :to => "user#expenses_log"
end

app/views/partials/dashboard/dashboard_modals/_add_expense_modal.html.slim
#addExpenseModal.modal[tabindex="-1" role="dialog"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        h5.modal-title
          | Add Expense
        button.modal-close.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
      .modal-body
          div#allUsers
            table.table.all_users_table
              thead
                tr
                  th[scope="row"]
                    | Users
              tbody
              -@all_users.each do |user|
                tr
                  td.sharedClickableRow [data-user_id="#{user[:id]}"]
                    = link_to user.first_name, "javascript:void(0)", :id=> "sharedUserLink"
      .modal-footer
          button.modal-close.btn.btn-secondary[type="button" data-dismiss="modal"]
            | Close
          button.btn.btn-primary[type="button"]
            | Save changes

app/views/partials/dashboard/dashboard_modals/_error_modal.html.slim
#errorModal.modal[tabindex="-1" role="dialog"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        h3.modal-title
          | Error
        button.modal-close.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | X
      .modal-body
          div#errorsList
            ul
              - unless @error.nil?
                li.error
                  = @error
              li.error

      .modal-footer
          button.modal-close.btn.btn-secondary[type="button" data-dismiss="modal"]
            | Close

app/views/partials/dashboard/dashboard_modals/_settle_expense_modal.html.slim
#settleExpenseModal.modal[tabindex="-1" role="dialog"]
  = form_tag user_settle_expense_path, :method => :post
    .modal-dialog[role="document"]
      .modal-content
        .modal-header
          h3.modal-title
            | Settle Expense
          button.modal-close.close[type="button" data-dismiss="modal" aria-label="Close"]
            span[aria-hidden="true"]
              | X
        .modal-body
            div#settleExpense
                table.table#settleExpensesTable
                  thead
                    tr
                      th[scope="row"]
                        | Amount
                      th[scope="row"]
                        | Borrowed From
                      th[scope="row"]
                        | Borrower
                      th[scope="row"]
                        | Date
                      th[scope="row"]
                        | Notes
                  tbody
                    tr
                      td.settleAmount
                      td.settleBorrowedFrom
                      td.settleBorrower
                      td.settleDateOfExpense
                      td.settleNotes
                        = text_area_tag :note, "", :class=> "form-control"
                      td.settleExpenseId
        .modal-footer
            button.btn
              = submit_tag "Settle Expense", data: { disable_with: "Settling Expense..." }, :class => "btn", :id => "settle_expense_submit"