config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "user#sign_in", :to => "user#sign_in"
  post "user/sign_in", :to => "sessions#create"
  post "user/sign_up", :to => "user#sign_up"
  get "user/sign_up", :to => "user#sign_up"
  get "user/sign_in", :to => "user#sign_in"
  delete "user/sign_out", :to => "sessions#destroy"
  get "user/dashboard", :to => "user#dashboard"
  get "user/expenses_with_user", :to => "user#expenses_with_user"
  get "user/friends_expenses", :to => "user#friends_expenses"

  get "user/add_expense", :to => "user#add_expense"
  post "user/add_expense", :to => "user#add_expense"

  get "user/settle_expense", :to => "user#settle_expense"
  post "user/settle_expense", :to => "user#settle_expense"
  get "user/all_expenses_log", :to => "user#expenses_log"
end

app/views/partials/dashboard/_expenses_with_user_table.html.slim
table.table#sharedExpensesTable
  thead
    tr
      th[scope="col"]
        | #
      th[scope="col"]
        | Borrowed From
      th[scope="col"]
        | Borrower
      th[scope="col"]
        | Amount
  tbody
    -(0..all_expenses.length-1).each do |i|
      tr class=(is_borrower?(all_expenses[i], user[:id]) ? 'red_row' : 'green_row')
        th[scope="row"]
          = i+1
        td
          = all_expenses[i][:borrowed_from_name]
        td
          = all_expenses[i][:borrower_name]
        td
          = all_expenses[i][:amount]

app/views/partials/dashboard/_friends_expense.html.slim
div#allUsers
  table.table.all_users_table
    thead
      tr
        th[scope="row"]
          | Users
    tbody
    -@all_users.each do |user|
      tr
        td.friendsClickableRow [data-user_id="#{user[:id]}"]
          = link_to user.first_name, "javascript:void(0)", :id=> "friendsUserLink"

div#friendsExpensesContainer

app/views/partials/dashboard/_friends_expenses_table.html.slim
table.table#friendsExpensesTable
  thead
    tr
      th[scope="col"]
        | #
      th[scope="col"]
        | Borrowed From
      th[scope="col"]
        | Borrower
      th[scope="col"]
        | Amount
  tbody
    -(0..all_expenses.length-1).each do |i|
      tr class=(is_borrower?(all_expenses[i], user) ? 'red_row' : 'green_row')
        th[scope="row"]
          = i+1
        td
          = all_expenses[i][:borrowed_from_name]
        td
          = all_expenses[i][:borrower_name]
        td
          = all_expenses[i][:amount]

app/views/partials/dashboard/_my_expense.html.slim
div#addSettleExpenses
  = link_to "Add an Expense", user_add_expense_path, :class=> "btn addExpenseModal" ,:id => "addExpenseTrigger"
  = link_to "All Expenses Log", user_all_expenses_log_path, :class=> "btn addExpenseModal" ,:id => "addExpenseTrigger"
table.table.my_expense
  thead
    tr
      th[scope="col"]
        | Total Balance
      th[scope="col"]
        | Total I Owe
      th[scope="col"]
        | Total Owed to me
  tbody
    tr
      td class=(@total_expense>=0.0 ? "green_row": "red_row")
        -if @total_expense > 0.0
            = "+ #{@total_expense.round(2)}"
        -elsif @total_expense <= 0.0
            = (@total_expense.to_f).round(2)
      td class=("red_row")
        = @user[:total_owe].nil? ? 0.0 : @user[:total_owe].round(2)
      td class=("green_row")
        = @user[:total_owed].nil? ? 0.0: @user[:total_owed].round(2)

h5
  b
    |Please select on borrowed (red rows) expense to settle)
table.table#allExpensesTable
  thead
    tr
      th[scope="col"]
        | #
      th[scope="col"]
        | Borrowed From
      th[scope="col"]
        | Borrower
      th[scope="col"]
        | Amount
      th[scope="col"]
        | Date
      th[scope="col"]
        | Bill description
  tbody
    -(0..@user_expenses.length-1).each do |i|
      tr data-expense-id = (@user_expenses[i][:id]) class=(is_borrower?(@user_expenses[i], @user[:id]) ? 'red_row settleExpenseClickable' : 'green_row')
        th[scope="row"]
          = i+1
        td
          = @user_expenses[i][:borrowed_from_name]
        td
          = @user_expenses[i][:borrower_name]
        td
          = @user_expenses[i][:amount]
        td
          = @user_expenses[i][:created_at].strftime("%a %d-%m-%y  %l:%M:%p")
        td
          = @user_expenses[i][:bill_desc]

app/views/partials/dashboard/_shared_expense.html.slim
div#allUsers
  table.table.all_users_table
    thead
      tr
        th[scope="row"]
          | Users
    tbody
    -@all_users.each do |user|
      tr
        td.sharedClickableRow [data-user_id="#{user[:id]}"]
          = link_to user.first_name, "javascript:void(0)", :id=> "sharedUserLink"

div#sharedExpenseContainer