config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "user#sign_in", :to => "user#sign_in"
  post "user/sign_in", :to => "sessions#create"
  post "user/sign_up", :to => "user#sign_up"
  get "user/sign_up", :to => "user#sign_up"
  get "user/sign_in", :to => "user#sign_in"
  delete "user/sign_out", :to => "sessions#destroy"
  get "user/dashboard", :to => "user#dashboard"
  get "user/expenses_with_user", :to => "user#expenses_with_user"
  get "user/friends_expenses", :to => "user#friends_expenses"

  get "user/add_expense", :to => "user#add_expense"
  post "user/add_expense", :to => "user#add_expense"

  get "user/settle_expense", :to => "user#settle_expense"
  post "user/settle_expense", :to => "user#settle_expense"
  get "user/all_expenses_log", :to => "user#expenses_log"
end

app/models/user.rb
class User < ApplicationRecord

  validates :password, :length => {:minimum => 8 }
  validates :email, :uniqueness => true
  validates :first_name, :uniqueness => true
  has_many :bills

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def password
    @password
  end

  def password=(raw)
    @password = raw
    self.password_digest = BCrypt::Password.create(raw)
  end

  def is_password?(raw)
    BCrypt::Password.new(password_digest).is_password?(raw)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  require_relative "../platform/session_application"
  require_relative "../platform/bill_application"
  require_relative "../platform/expense_application"
  require_relative "../platform/session_application"

  include SessionApplication
  include BillApplication
  include ExpenseApplication
  include SessionApplication

  respond_to :html, :js

  def home
    @user = User.new
  end

  def sign_in
    #TODO Remove request.post?
    if request.post?
    elsif request.get?
      redirect_to user_dashboard_path if logged_in?
    end
  end

  def expenses_with_user
    user = get_user_params_expense
    current_user = current_user()
    @all_expenses = get_all_expenses_bet_two_users(user, current_user[:id])
    render json: { expenses_table: render_to_string('partials/dashboard/_expenses_with_user_table', layout: false, locals: { all_expenses: @all_expenses, user: current_user}) }
  end

  def friends_expenses
    user = get_user_params_expense
    current_user = current_user()
    @all_expenses = get_all_expenses_of_user_id(user)
    render json: { expenses_table: render_to_string('partials/dashboard/_friends_expenses_table', layout: false, locals: { all_expenses: @all_expenses, user: user}) }
  end

  def sign_up
    if request.post?
      begin
        create_new_user(get_user_params)
        redirect_to user_dashboard_path
      rescue InvalidCredentialsError => e
        flash.now[:notice] = e.message
        render user_sign_up_path
      rescue InvalidEmailError => e
        flash.now[:notice] = e.message
        render user_sign_up_path
      rescue UserSignUpError => e
        flash.now[:notice] = e.message
        render user_sign_up_path
      end
    elsif request.get?
      @user = User.new
    end
  end

  def dashboard
    @user = current_user
    @new_expense = Expense.new
    @all_users = get_all_users_except(@user[:id])
    @total_expense = ((@user[:total_owed].nil? ? 0:@user[:total_owed]) - (@user[:total_owe].nil? ? 0:@user[:total_owe]))
    @user_expenses = get_all_expenses_of_user_id(@user[:id])
    @user_borrowed = get_all_expenses_as_borrower_service(@user[:id])
  end

  def add_expense
    if request.post?
      begin
        validate_add_expense_params(params)
        no_of_parts =  params[:participants].size
        bill_params = {
          :paid_by => current_user,
          :amount =>  params[:bill_amount],
          :no_parts => params[:participants].size+1,
          :desc => params[:desc]
        }
        bill = add_bill(bill_params)
        if(!params[:unequal].nil? && params[:unequal] == "true")
          share_perc = params[:shares]
          shares = []
          share_perc.each do |share|
            shares.push(share.to_f)
          end
          add_expenses(bill, params[:participants], true, shares)
        else
          add_expenses(bill, params[:participants], false, [])
        end
        redirect_to user_dashboard_path
      rescue => error
        @user = current_user
        @new_expense = Expense.new
        @all_users = get_all_users_except(@user[:id])
        @total_expense = ((@user[:total_owed].nil? ? 0:@user[:total_owed]) - (@user[:total_owe].nil? ? 0:@user[:total_owe]))
        @user_expenses = get_all_expenses_of_user_id(@user[:id])
        @user_borrowed = get_all_expenses_as_borrower_service(@user[:id])
        @errors = error.message
        render user_dashboard_path
      end
    elsif request.get?
      @current_user = current_user
      @all_users = get_all_users_except(@current_user[:id])
      @new_expense = Expense.new
    end
  end


  def settle_expense
    if request.get?
      get_settle_expense_params
      @expense = get_expense_by_id(params[:expense_id])
      render :json => {:success => true, :expense => @expense}
    elsif request.post?
      get_settle_expense_params
      settle_an_expense_with_id(params[:expense_id], params[:note])
      redirect_to user_dashboard_path
    end
  end

  def expenses_log
    @user = current_user
    @expenses_log = get_all_expenses_log(@user.id)
  end

private
  def get_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def get_user_params_expense
    params.require(:user_id)
  end

  def get_add_expense_params
    params.permit(:unequal)
    params.permit(:bill_amount)
    params.permit(:shares)
    params.permit(:participants)
    params.permit(:desc)
  end

  def get_settle_expense_params
    params.permit(:expense_id)
    params.permit(:note)
  end
end

app/helpers/user_helper.rb
module UserHelper

  def validate_email(email)
    result = email =~ User::VALID_EMAIL_REGEX
    if(email == "")
      raise InvalidEmailError.new("Please enter an email id to sign up!")
    elsif(result.nil?)
      raise InvalidEmailError.new("Invalid email format. Please try again.")
    end
  end

  def is_borrower?(expense, user_id)
    if(expense[:borrower_id].to_s == user_id.to_s)
      return true
    end
  end

  def validate_sign_up_params(params)
    if(params[:first_name] == "")
      raise UserSignUpError.new("Please enter your first name")
    elsif params[:last_name] == ""
      raise UserSignUpError.new("Please enter your last name")
    end
  end
end

app/views/user/add_expense.html.slim
= render "/partials/navbar/navbar"
= render "/partials/dashboard/dashboard_modals/error_modal"
h1
  = "Hi #{@current_user[:first_name]}"

.dashboardContainer
  =form_tag user_add_expense_path, method: :post
    div#allUsers.add_expense_users
      table.table.all_users_table
        thead
          tr
            th[scope="row"]
              |Select Users
        tbody
        -@all_users.each do |user|
          .form_group
            tr
              td [data-user_id="#{user[:id]}"]
                = label_tag "add_user_to_expense_#{user[:id]}", "#{user.first_name}", :class => "participant_label"
                = check_box_tag "participants[]", "#{user.id}",false, :multiple => true, :class => "participants_checkbox", :data => {:user_name => user.first_name, :user_id => user.id},:id=> "add_user_to_expense_#{user.id}", :style=> "float: right;"
    div#addExpenseInput
      h3
        | Add an Expense
      .form_group
        = check_box_tag "unequal", true, true, :class => "unequal_checkbox", :id=>"unequal_split"
        = label_tag "unequal", "Unequal Split ?", :class => "unequal_label"
      .form_group
        = label_tag "bill_amount", "Bill Amount"
        = text_field_tag "bill_amount", " ",:class => "form-control add_expense_bill_input "
      #unequalSplit

      .form_group
        = label_tag "desc", "Bill Description", :style=>"margin-top:2%;"
        = text_area_tag :desc, "", :class=> "form-control add_expense_desc"
      .form_group
        = submit_tag "Add Expense", data: { disable_with: "Adding Expense..." }, :class => "btn", :id => "add_expense_submit"

= javascript_pack_tag 'add_expense'

app/views/user/dashboard.html.slim
= render :partial => "/partials/navbar/navbar"
- if !@errors.nil?
  .alert.alert-danger
    = @errors
- else
  h2
    = "Hi #{@user[:first_name]} !"
.dashboardContainer
  ul.nav.nav-tabs
    li.nav-item#allExpensesTab
      a#allExpenses.nav-link.active[aria-current="page" href="javascript:void(0)"]
        | My Current Expenses
    li.nav-item#sharedExpensesTab
      a.nav-link[href="javascript:void(0)"]
        | Shared Expenses
    li.nav-item#friendsExpensesTab
      a.nav-link.disabled[href="javascript:void(0)" tabindex="-1" aria-disabled="true"]
        | Friends Expense
  div#dashboardWrapper

  div#myExpense
    = render "/partials/dashboard/my_expense"
    = render "/partials/dashboard/dashboard_modals/add_expense_modal"
    = render "/partials/dashboard/dashboard_modals/settle_expense_modal"
  div#sharedExpense
    = render "/partials/dashboard/shared_expense"
  div#friendsExpense
    = render "/partials/dashboard/friends_expense"


= javascript_pack_tag 'dashboard'
= javascript_pack_tag 'settle_expense'

app/views/user/expenses_log.html.slim
= render :partial => "/partials/navbar/navbar"
.dashboardContainer
  table.table#allExpensesLogTable
    thead
      tr
        th[scope="col"]
          | #
        th[scope="col"]
          | Borrowed From
        th[scope="col"]
          | Borrower
        th[scope="col"]
          | Amount
        th[scope="col"]
          | Date
        th[scope="col"]
          | Bill description
        th[scope="col"]
          | Expense Settling Note
    tbody
      -(0..@expenses_log.length-1).each do |i|
        tr data-expense-id = (@expenses_log[i][:id]) class=((@expenses_log[i][:settled] == true)? "blue_row" : is_borrower?(@expenses_log[i], @user[:id]) ? 'red_row' : 'green_row')
          th[scope="row"]
            = i+1
          td
            = @expenses_log[i][:borrowed_from_name]
          td
            = @expenses_log[i][:borrower_name]
          td
            = @expenses_log[i][:amount]
          td
            = @expenses_log[i][:created_at].strftime("%a %d-%m-%y  %l:%M:%p")
          td
            = @expenses_log[i][:bill_desc]
          td[scope="col"]
            = @expenses_log[i][:notes].nil? ? "NA" : @expenses_log[i][:notes]

app/views/user/sign_in.html.slim
.sign_in
  - flash.each do |type, message|
    .alert.alert-danger *{:role => "alert"}
      = message
  h1.sign_in_head
    = "Sign In"
  =form_for User.new, :url => user_sign_in_path, :method => 'post' do |f|
    .form-row.mt-4
      .form-group.col-md-6
        = f.email_field :email, :class=> "email", :class=>"form-control text_box", :placeholder=>"Email"
        = f.password_field :password, :class=>"password" ,:class=>"form-control text_box", :placeholder=>"Password"
        = f.submit "Login",:class=>"btn mt-2 form-submit blue_btn"
        = link_to "Sign Up", user_sign_up_path, :class=> "sign_up_link"

app/views/user/sign_up.html.slim
.sign_up
  - flash.each do |type, message|
    .alert.alert-danger *{:role => "alert"}
      = message
h1.sign_up_head
  = "Sign Up"
=form_for User.new, :url => user_sign_up_path, :method => 'post' do |f|
  .form-row.mt-4
    .form-group.col-md-6
      = f.text_field :first_name, :class=> "first_name", :class=>"form-control text_box", :placeholder=>"First Name"
      = f.text_field :last_name, :class=> "last_name", :class=>"form-control text_box", :placeholder=>"Last Name"
      = f.email_field :email, :class=> "email", :class=>"form-control text_box", :placeholder=>"Email"
      = f.password_field :password, :class=>"password" ,:class=>"form-control text_box", :placeholder=>"Password"
      = f.submit "Sign Up",:class=>"btn mt-2 form-submit blue_btn"